[package]
name = "burrtype"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
itertools = "0.11"

[dev-dependencies]
burrtype_derive = { path = "./burrtype_derive" }