[package]
name = "burrtype"
version = "0.1.0"
edition = "2021"

[features]
default = ["typescript"]
typescript = []

[dependencies]
bevy_reflect = "0.11"
thiserror = "1.0"
itertools = "0.11"
Inflector = "0.11"
path_macro = "1.0"
path-slash = "0.2"

[dev-dependencies]
anyhow = "1.0"