[package]
name = "burrtype_internal"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0", features = ["span-locations"] }
syn = { version = "2.0", features = ["full", "extra-traits"] }