[package]
name = "burrtype_internal"
version = "0.2.0"
edition = "2021"

[features]
default = []
docs = []

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }