[package]
name = "burrtype_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "burrtype_derive"
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
paste = "1.0"
Inflector = "0.11"

[dev-dependencies]
path_macro = "1.0"