[package]
name = "test-server"
version = "0.4.0"
edition = "2021"

[dependencies]
sandbox = { path = ".." }
anyhow = "1.0"
axum = "0.6"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
rust_decimal = "1.32"